language: java
jdk: oraclejdk8
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      - secure: pNrbw95K+K42UnZHEWZ6qKqfkIKJTlLT9iFLNKWDM43cytUZX/gzheNQNze3pZSqmqkWHnVCCDEL/mMVjYRJgfggbLiuR+UGXVbdTPNVr0GfkSNIPpUQ6lo5dxIK/qtHXfDuheetnAmiDk1UBRBnWVbYlfGaXAEEVLg+nqNT+fOzwGmNyjQbY02sLbCl44TVMz+g+Vcdz1UkzSb235mXLfoGtVIbMywzyPzJPEhVfRFuWOpUZViMIYc8zg90IMywZJLmHJfVIZObbeXR30jglKxldqW7GrYrAL4jdkqOAVZE1Pzo0gGNO+zz1ZWRayyZzmsLINkLNpy7Fd2AfMtcuUMppgZMIRxmu9IrG6p50/RBhPbdQi7NlKQMeupYHapOObwVKS/mZ7fGIDO7WyCJ1SsVtbzUFFxN4FLHVprJGWbeNeKF7nRntjD+bOJssmvVnpKl/K2wbCfzQ9Mk5X1w+PNWC4Ozngrp8VwVTc0oVPCJvkDHOL9kQjtJDnN9OuNtbIELEAWRkeckRZZjAYSKb6Q6kpzHUPaniL+1W2xFJKRT3M1f+f8bBs5qXLLrNW+ST/Fq3OrK0NjtuqmLecd4uyoCEcceKFd7IVeesSqddKSk9iCZf+Cs/OvlmfBoD3dThzKzxdo+LE2L/SRFal7WZ/yp7/WwvK2PqkF5L8OcDpc=
